### ISSUE TITLE
skydns stopped working after update

### ISSUE THREAD

**Issue by heidarxvpn** [skynetservices/skydns#162]
Hi!

I was using skydns on my servers and it was working fine. Then I pulled the newer image and it stopped working altogether. It runs (process shows in ps) but it doesn't listen on the network. As far as I know it listens on loopback by default or on a given IP and it does neither. This leads me to think that something is wrong.

Running with verbose didn't help since it doesn't listen on the network so it never got to the point where it would accept connections. We could really do with more logging when verbose is set.

I've downgraded for now and the old version works fine. I'll upgrade again based on the outcome of this ticket.

Thanks!

docker-compose.yml entry
```
skydns:
  image: skynetservices/skydns:latest
  command: -rcache-ttl 0
  environment:
    ETCD_MACHINES: "http://172.17.42.1:4001"
    SKYDNS_DOMAIN: "docker."
    SKYDNS_ADDR: "0.0.0.0:53"
    SKYDNS_NAMESERVERS: "8.8.8.8:53,8.8.4.4:53"
  ports:
    - 172.17.42.1:53:53/udp
  volumes:
    - /bin/netstat:/netstat
    - /bin/ps:/ps
```
